"""TensorMux Live Inference Provider Client (GLM-4.7-Flash).

Implements OpenAI-compatible inference connection to TensorMux (https://api.tensormux.com/v1)
with full support for:
- Model: glm-4-7-flash
- Standard tool-calling protocol (formatting, receiving, returning tool messages)
- GLM-4.7-Flash reasoning tokens extraction ('reasoning' message field)
- Strict max_tokens >= 400 enforcement to prevent reasoning token truncation
- Structured JSON output parsing (raw JSON, markdown code blocks)
- Accurate token counting and live USD cost calculation
- Multi-turn tool execution loop
"""

from __future__ import annotations

import json
import logging
import os
import re
from typing import Any, Callable, Dict, List, Optional, Tuple, Union
import httpx
from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger(__name__)

# Default Constants
DEFAULT_TENSORMUX_BASE_URL = "https://api.tensormux.com/v1"
DEFAULT_TENSORMUX_MODEL = "glm-4-7-flash"
MIN_REASONING_MAX_TOKENS = 400

# Cost rates per 1M tokens ($0.10 per 1M tokens for glm-4-7-flash)
DEFAULT_INPUT_COST_PER_MILLION = 0.10
DEFAULT_OUTPUT_COST_PER_MILLION = 0.10


class ToolCall(BaseModel):
    """Encapsulates a model-generated tool call."""

    model_config = ConfigDict(extra="ignore")

    id: str = Field(description="Unique tool call identifier (e.g., call_xxx)")
    name: str = Field(description="Target tool/function name")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Parsed JSON arguments dictionary")
    raw_arguments: str = Field(default="{}", description="Raw serialized JSON arguments string")


class UsageInfo(BaseModel):
    """Token usage metrics and derived cost calculation."""

    prompt_tokens: int = Field(default=0, description="Tokens in input prompt")
    completion_tokens: int = Field(default=0, description="Tokens generated by model")
    total_tokens: int = Field(default=0, description="Total tokens consumed")
    reasoning_tokens: int = Field(default=0, description="Internal reasoning / CoT tokens")
    cost_usd: float = Field(default=0.0, description="Calculated live inference cost in USD")


class TensorMuxResponse(BaseModel):
    """Structured response payload from TensorMux inference."""

    model_config = ConfigDict(extra="ignore")

    model: str = Field(default=DEFAULT_TENSORMUX_MODEL, description="Model identifier")
    role: str = Field(default="assistant", description="Message role")
    content: Optional[str] = Field(default=None, description="Assistant text response")
    reasoning: Optional[str] = Field(default=None, description="GLM-4.7-Flash internal reasoning content")
    tool_calls: List[ToolCall] = Field(default_factory=list, description="Requested tool invocations")
    finish_reason: Optional[str] = Field(default=None, description="Finish reason (e.g. stop, tool_calls)")
    usage: UsageInfo = Field(default_factory=UsageInfo, description="Token usage and cost accounting")
    raw_response: Dict[str, Any] = Field(default_factory=dict, description="Raw API response dictionary")

    @property
    def has_tool_calls(self) -> bool:
        """True if the model requested one or more tool calls."""
        return len(self.tool_calls) > 0

    @property
    def has_reasoning(self) -> bool:
        """True if GLM-4.7-Flash produced reasoning tokens."""
        return bool(self.reasoning and self.reasoning.strip())

    @property
    def cost_usd(self) -> float:
        """Total calculated inference cost for this response."""
        return self.usage.cost_usd

    def parse_json(self) -> Dict[str, Any]:
        """Extract and parse structured JSON from the response content.

        Returns:
            Parsed dictionary.

        Raises:
            ValueError: If content does not contain valid JSON.
        """
        if not self.content:
            raise ValueError("Cannot parse JSON: response content is empty or None.")
        return parse_json_output(self.content)


def calculate_tensormux_cost(
    prompt_tokens: int,
    completion_tokens: int,
    input_cost_per_m: float = DEFAULT_INPUT_COST_PER_MILLION,
    output_cost_per_m: float = DEFAULT_OUTPUT_COST_PER_MILLION,
) -> float:
    """Calculate live USD cost based on token counts and rates per million tokens.

    Args:
        prompt_tokens: Number of prompt/input tokens.
        completion_tokens: Number of completion/output tokens.
        input_cost_per_m: Input price per 1M tokens in USD.
        output_cost_per_m: Output price per 1M tokens in USD.

    Returns:
        Total cost in USD rounded to 8 decimal places.
    """
    input_cost = (prompt_tokens / 1_000_000.0) * input_cost_per_m
    output_cost = (completion_tokens / 1_000_000.0) * output_cost_per_m
    return round(input_cost + output_cost, 8)


def parse_json_output(text: str) -> Dict[str, Any]:
    """Parse structured JSON from raw string, handling markdown code blocks and whitespace.

    Args:
        text: Raw string containing JSON or markdown-fenced JSON.

    Returns:
        Parsed JSON dictionary or list wrapped in a dict.

    Raises:
        ValueError: If no valid JSON could be parsed.
    """
    stripped = text.strip()

    # 1. Direct parse attempt
    try:
        data = json.loads(stripped)
        if isinstance(data, dict):
            return data
        elif isinstance(data, list):
            return {"items": data}
        return {"value": data}
    except json.JSONDecodeError:
        pass

    # 2. Extract from markdown code blocks: ```json ... ``` or ``` ... ```
    code_block_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", stripped, re.IGNORECASE)
    if code_block_match:
        block_content = code_block_match.group(1).strip()
        try:
            data = json.loads(block_content)
            if isinstance(data, dict):
                return data
            elif isinstance(data, list):
                return {"items": data}
            return {"value": data}
        except json.JSONDecodeError:
            pass

    # 3. Extract substring between outermost { and }
    first_brace = stripped.find("{")
    last_brace = stripped.rfind("}")
    if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
        candidate = stripped[first_brace:last_brace + 1]
        try:
            data = json.loads(candidate)
            if isinstance(data, dict):
                return data
        except json.JSONDecodeError:
            pass

    raise ValueError(f"Failed to parse structured JSON from text: {text[:200]}...")


def format_tool_definition(tool: Any) -> Dict[str, Any]:
    """Convert a ToolDefinition or schema dict into OpenAI-compatible tool format.

    Args:
        tool: Either a ToolDefinition, a dict conforming to ToolDefinition,
              or an existing OpenAI function tool dict.

    Returns:
        Standard OpenAI tool dictionary:
        {"type": "function", "function": {"name": ..., "description": ..., "parameters": ...}}
    """
    # Already formatted as OpenAI tool
    if isinstance(tool, dict) and tool.get("type") == "function" and "function" in tool:
        return tool

    if hasattr(tool, "name") and hasattr(tool, "description") and hasattr(tool, "parameters"):
        return {
            "type": "function",
            "function": {
                "name": tool.name,
                "description": tool.description,
                "parameters": tool.parameters,
            },
        }

    if isinstance(tool, dict):
        name = tool.get("name", "unnamed_tool")
        description = tool.get("description", "")
        parameters = tool.get("parameters", {"type": "object", "properties": {}})
        return {
            "type": "function",
            "function": {
                "name": name,
                "description": description,
                "parameters": parameters,
            },
        }

    raise ValueError(f"Cannot format object of type {type(tool)} as OpenAI tool definition.")


def create_tool_message(
    tool_call_id: str,
    content: Any,
    name: Optional[str] = None
) -> Dict[str, Any]:
    """Create a standard OpenAI-compatible tool response message.

    Args:
        tool_call_id: The ID of the tool call being answered.
        content: The result of tool execution (dict, list, string, or number).
        name: Optional name of the tool function.

    Returns:
        Dict formatted as a tool role message.
    """
    if isinstance(content, (dict, list)):
        serialized = json.dumps(content, ensure_ascii=False)
    else:
        serialized = str(content)

    msg: Dict[str, Any] = {
        "role": "tool",
        "tool_call_id": tool_call_id,
        "content": serialized,
    }
    if name:
        msg["name"] = name
    return msg


class TensorMuxClient:
    """OpenAI-compatible live inference client for TensorMux (GLM-4.7-Flash)."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout: float = 60.0,
        input_cost_per_m: float = DEFAULT_INPUT_COST_PER_MILLION,
        output_cost_per_m: float = DEFAULT_OUTPUT_COST_PER_MILLION,
        http_client: Optional[httpx.Client] = None,
    ):
        """Initialize the TensorMux provider client.

        Args:
            api_key: TensorMux API key (falls back to TENSORMUX_API_KEY env var).
            base_url: Inference gateway URL (falls back to TENSORMUX_BASE_URL or default).
            model: Model name (defaults to glm-4-7-flash).
            timeout: Request timeout in seconds.
            input_cost_per_m: Input cost per 1M tokens in USD.
            output_cost_per_m: Output cost per 1M tokens in USD.
            http_client: Optional custom httpx.Client (e.g., for mock transports in tests).
        """
        self.api_key = api_key or os.environ.get("TENSORMUX_API_KEY", "")
        self.base_url = (base_url or os.environ.get("TENSORMUX_BASE_URL") or DEFAULT_TENSORMUX_BASE_URL).rstrip("/")
        self.model = model or os.environ.get("TENSORMUX_MODEL") or DEFAULT_TENSORMUX_MODEL
        self.timeout = timeout
        self.input_cost_per_m = input_cost_per_m
        self.output_cost_per_m = output_cost_per_m
        self._custom_client = http_client

    def _get_headers(self) -> Dict[str, str]:
        """Construct standard HTTP authentication and content headers."""
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        return headers

    def enforce_max_tokens(self, max_tokens: Optional[int]) -> int:
        """Enforce strict max_tokens >= 400 to prevent GLM-4.7-Flash reasoning truncation.

        Args:
            max_tokens: Requested max tokens or None.

        Returns:
            Enforced max_tokens value, guaranteed >= 400.
        """
        if max_tokens is None:
            return 4096
        if max_tokens < MIN_REASONING_MAX_TOKENS:
            logger.warning(
                f"Requested max_tokens ({max_tokens}) is less than {MIN_REASONING_MAX_TOKENS}. "
                f"Clamping to {MIN_REASONING_MAX_TOKENS} to prevent GLM-4.7-Flash reasoning token truncation."
            )
            return MIN_REASONING_MAX_TOKENS
        return max_tokens

    def chat_completion(
        self,
        messages: List[Dict[str, Any]],
        tools: Optional[List[Any]] = None,
        tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
        max_tokens: Optional[int] = 4096,
        temperature: float = 0.7,
        response_format: Optional[Dict[str, Any]] = None,
        model: Optional[str] = None,
        **extra_kwargs: Any,
    ) -> TensorMuxResponse:
        """Execute a synchronous chat completion call to TensorMux.

        Args:
            messages: List of message dictionaries with 'role' and 'content'.
            tools: Optional list of tools (ToolDefinition or OpenAI function schemas).
            tool_choice: 'auto', 'none', 'required', or specific tool selector.
            max_tokens: Maximum tokens to generate (strictly enforced >= 400).
            temperature: Sampling temperature.
            response_format: Optional format specification (e.g., {"type": "json_object"}).
            model: Model override (defaults to client model).
            **extra_kwargs: Additional parameters forwarded to the API.

        Returns:
            TensorMuxResponse with content, reasoning, tool_calls, and token usage.
        """
        enforced_max_tokens = self.enforce_max_tokens(max_tokens)
        target_model = model or self.model

        payload: Dict[str, Any] = {
            "model": target_model,
            "messages": messages,
            "max_tokens": enforced_max_tokens,
            "temperature": temperature,
            **extra_kwargs,
        }

        if tools:
            payload["tools"] = [format_tool_definition(t) for t in tools]
            if tool_choice:
                payload["tool_choice"] = tool_choice
            else:
                payload["tool_choice"] = "auto"

        if response_format:
            payload["response_format"] = response_format

        url = f"{self.base_url}/chat/completions"
        headers = self._get_headers()

        if self._custom_client is not None:
            response = self._custom_client.post(url, json=payload, headers=headers, timeout=self.timeout)
            response.raise_for_status()
            data = response.json()
        else:
            with httpx.Client(timeout=self.timeout) as client:
                response = client.post(url, json=payload, headers=headers)
                response.raise_for_status()
                data = response.json()

        return self._parse_api_response(data, target_model)

    async def achat_completion(
        self,
        messages: List[Dict[str, Any]],
        tools: Optional[List[Any]] = None,
        tool_choice: Optional[Union[str, Dict[str, Any]]] = None,
        max_tokens: Optional[int] = 4096,
        temperature: float = 0.7,
        response_format: Optional[Dict[str, Any]] = None,
        model: Optional[str] = None,
        **extra_kwargs: Any,
    ) -> TensorMuxResponse:
        """Execute an asynchronous chat completion call to TensorMux."""
        enforced_max_tokens = self.enforce_max_tokens(max_tokens)
        target_model = model or self.model

        payload: Dict[str, Any] = {
            "model": target_model,
            "messages": messages,
            "max_tokens": enforced_max_tokens,
            "temperature": temperature,
            **extra_kwargs,
        }

        if tools:
            payload["tools"] = [format_tool_definition(t) for t in tools]
            if tool_choice:
                payload["tool_choice"] = tool_choice
            else:
                payload["tool_choice"] = "auto"

        if response_format:
            payload["response_format"] = response_format

        url = f"{self.base_url}/chat/completions"
        headers = self._get_headers()

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()

        return self._parse_api_response(data, target_model)

    def _parse_api_response(self, data: Dict[str, Any], target_model: str) -> TensorMuxResponse:
        """Parse raw API JSON into a strongly typed TensorMuxResponse."""
        choices = data.get("choices", [])
        if not choices:
            raise ValueError(f"TensorMux API response contains no choices: {data}")

        choice = choices[0]
        message = choice.get("message", {})
        content = message.get("content")

        # Extract GLM-4.7-Flash reasoning tokens from 'reasoning' or 'reasoning_content'
        reasoning = message.get("reasoning") or message.get("reasoning_content")

        # Parse tool calls
        raw_tool_calls = message.get("tool_calls", [])
        tool_calls: List[ToolCall] = []
        for rtc in raw_tool_calls:
            tc_id = rtc.get("id", "")
            func = rtc.get("function", {})
            fname = func.get("name", "")
            raw_args = func.get("arguments", "{}")

            if isinstance(raw_args, str):
                try:
                    args_dict = json.loads(raw_args)
                except Exception:
                    args_dict = {"raw": raw_args}
            elif isinstance(raw_args, dict):
                args_dict = raw_args
                raw_args = json.dumps(raw_args)
            else:
                args_dict = {}
                raw_args = "{}"

            tool_calls.append(ToolCall(
                id=tc_id,
                name=fname,
                arguments=args_dict,
                raw_arguments=raw_args,
            ))

        finish_reason = choice.get("finish_reason")

        # Parse usage and calculate cost
        raw_usage = data.get("usage", {})
        prompt_tokens = int(raw_usage.get("prompt_tokens", 0))
        completion_tokens = int(raw_usage.get("completion_tokens", 0))
        total_tokens = int(raw_usage.get("total_tokens", prompt_tokens + completion_tokens))

        # Check reasoning tokens if reported in completion_tokens_details
        reasoning_tokens = 0
        details = raw_usage.get("completion_tokens_details")
        if isinstance(details, dict):
            reasoning_tokens = int(details.get("reasoning_tokens", 0))

        cost_usd = calculate_tensormux_cost(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            input_cost_per_m=self.input_cost_per_m,
            output_cost_per_m=self.output_cost_per_m,
        )

        usage = UsageInfo(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total_tokens,
            reasoning_tokens=reasoning_tokens,
            cost_usd=cost_usd,
        )

        return TensorMuxResponse(
            model=data.get("model", target_model),
            role=message.get("role", "assistant"),
            content=content,
            reasoning=reasoning,
            tool_calls=tool_calls,
            finish_reason=finish_reason,
            usage=usage,
            raw_response=data,
        )

    def run_agent_turn(
        self,
        messages: List[Dict[str, Any]],
        tools: List[Any],
        tool_executor_fn: Callable[[str, Dict[str, Any]], Any],
        max_iterations: int = 5,
        max_tokens: Optional[int] = 4096,
        temperature: float = 0.7,
    ) -> Tuple[TensorMuxResponse, List[Dict[str, Any]], float]:
        """Execute a multi-step tool-calling conversational agent loop.

        Args:
            messages: Initial conversation history.
            tools: Registered tool definitions available to the agent.
            tool_executor_fn: Callable taking (tool_name, arguments_dict) and returning result.
            max_iterations: Maximum tool calling round trips.
            max_tokens: Max tokens per model call.
            temperature: Model temperature.

        Returns:
            Tuple of (Final TensorMuxResponse, Updated message history, Total cumulative cost USD).
        """
        history = list(messages)
        total_cost_usd = 0.0
        iteration = 0

        while iteration < max_iterations:
            iteration += 1
            response = self.chat_completion(
                messages=history,
                tools=tools,
                max_tokens=max_tokens,
                temperature=temperature,
            )
            total_cost_usd += response.cost_usd

            # Build assistant message object for history
            assistant_msg: Dict[str, Any] = {"role": "assistant"}
            if response.content is not None:
                assistant_msg["content"] = response.content
            if response.reasoning is not None:
                assistant_msg["reasoning"] = response.reasoning

            if response.has_tool_calls:
                assistant_msg["tool_calls"] = [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {
                            "name": tc.name,
                            "arguments": tc.raw_arguments,
                        },
                    }
                    for tc in response.tool_calls
                ]
                history.append(assistant_msg)

                # Execute each tool and append tool messages
                for tc in response.tool_calls:
                    try:
                        tool_result = tool_executor_fn(tc.name, tc.arguments)
                    except Exception as exc:
                        tool_result = {"error": f"Tool execution failed: {str(exc)}"}

                    tool_msg = create_tool_message(
                        tool_call_id=tc.id,
                        content=tool_result,
                        name=tc.name,
                    )
                    history.append(tool_msg)
            else:
                history.append(assistant_msg)
                return response, history, round(total_cost_usd, 8)

        # If loop reached max iterations, return current response
        return response, history, round(total_cost_usd, 8)
